### ISSUE TITLE
gpu memory usage

### ISSUE THREAD

**Issue by chn52979** [Suoivy/LPD-net#2]
Hi, I am trying to use a 1080Ti to train the network, but it seems to be out of memory. Could you tell me how much memory it need and how long does it take to train this model？

**Comment by Suoivy** [comment]
Hi, I trained this model on one GTX 1080Ti with 11G memory, and it took almost four days to get the best result. If it's out of the memory, you can change the positives and negatives number per query. Currently, the `positives_per_query = 2` and the `negatives_per_query = 14`, and set the negatives = 12 or 13 in ArgumentParser of the `train_lpdnet.py` may works for this issue.
regards,
Suo

**Comment by chn52979** [comment]
@Suoivy Thanks.I have sovled this problem.
